project:
  type: website
  render:
    - "*.ipynb"

format:
  html:
    toc: true
    toc-depth: 5
    css: styles.css
    page-layout: full
    code-block-bg: true
    code-overflow: wrap
    code-line-numbers: false
    monofont: D2Coding
    language:
      crossref-tbl-title: "표"
    mermaid:
      theme: neutral
    include-in-header:
      text: |
        <script type="text/javascript">
        // !로 시작하는 파이썬 코드에서 ! 삭제
        document.addEventListener('DOMContentLoaded', () => {
          const allOps = document.querySelectorAll(
            'div.cell div.sourceCode.cell-code pre.sourceCode.python code span.op:first-of-type'
          );
          allOps.forEach(el => {
            if (el.innerHTML === '!') {
              el.innerHTML = '';
              const dollarSpan = document.createElement('span');
              dollarSpan.classList.add('bash_prompt');
              el.parentNode.parentNode.insertBefore(dollarSpan, el.parentNode);
            }
          });
          // || true 로 끝나는 bash 코드에서 || true 삭제
          const allOrTrue = document.querySelectorAll(
            'div.cell div.sourceCode.cell-code pre.sourceCode.bash code span:last-of-type'
          );
          allOrTrue.forEach(span => {
            let text = span.textContent;
            if (text.endsWith('|| true')) {
              span.textContent = text.slice(0, -8);
            }
          });
        });
        </script>

bibliography: references.bib
reference-location: margin

website:
  title: "Git Book"
  site-url: https://gitbook.madebykim.kr/
  google-analytics: G-QGSN4T24D9
  sidebar:
    style: "docked"
    search: true
    contents:
      - "index.ipynb"
      - "command.ipynb"
      - section: "사용자용 기초"
        contents:
        - "config.ipynb"
        - "repo.ipynb"
        - "basic.ipynb"
        - "internal.ipynb"
        - "commit.ipynb"
        - "branch.ipynb"
        - "checkout.ipynb"
        - "reset.ipynb"
        - "stash.ipynb"
        - "merge.ipynb"
        - "conflict.ipynb"
        - "remote_diverged.ipynb"
        - "ignore.ipynb"
        - "cowork.ipynb"
      - section: "관리자용 고급"
        contents:
        - "indexfile.ipynb"
      - section: "부록"
        contents:
        - "reference.ipynb"
