project:
  type: website
  render:
    - "*.ipynb"

format:
  html:
    toc: true
    toc-depth: 5
    css: styles.css
    page-layout: full
    code-block-bg: true
    code-overflow: wrap
    code-line-numbers: false
    monofont: D2Coding
    language:
      crossref-tbl-title: "표"
    mermaid:
      theme: neutral
    filters:
      - clean-code.lua

bibliography: references.bib
reference-location: margin

website:
  title: "Git Book"
  site-url: https://gitbook.madebykim.kr/
  google-analytics: G-QGSN4T24D9
  sidebar:
    style: "docked"
    search: true
    contents:
      - "index.ipynb"
      - section: "사용자용 기초"
        contents:
        - "intro.ipynb"
        - "git_command.ipynb"
        - "repo.ipynb"
        - "config.ipynb"
        - "basic.ipynb"
        - "internal.ipynb"
        - "view.ipynb"
        - "branch.ipynb"
        - "checkout.ipynb"
        - "reset.ipynb"
        - "stash.ipynb"
        - "merge.ipynb"
        - "conflict.ipynb"
        - "remote_diverged.ipynb"
        - "ignore.ipynb"
        - "cowork.ipynb"
      - section: "관리자용 고급"
        contents:
        - "gitfile.ipynb"
        - "indexfile.ipynb"
        - "pack.ipynb"
      - section: "부록"
        contents:
        - "reference.ipynb"

filters:
  - site-toc.lua
